// js/summary.js

// --- Aggregated Summary State ---
// let aggregatedChartInstance = null; // REMOVED: Already declared in state.js

/**
 * Generates aggregated summary data for a given date range.
 * @param {string} startDateStr - Start date in 'YYYY-MM-DD' format.
 * @param {string} endDateStr - End date in 'YYYY-MM-DD' format.
 * @returns {object} - Aggregated data: { totals: {projectId: totalMinutes}, daily: {'YYYY-MM-DD': {projectId: dailyMinutes}}, dateLabels: ['YYYY-MM-DD', ...] }
 */
function generateAggregatedSummary(startDateStr, endDateStr) {
    const summaryData = {
        totals: {}, // { projectId: totalMinutes }
        daily: {},  // { 'YYYY-MM-DD': { projectId: dailyMinutes } }
        dateLabels: [] // Array of 'YYYY-MM-DD' strings in the range
    };

    // Use Luxon for reliable date handling
    const startDt = luxon.DateTime.fromISO(startDateStr);
    let endDt = luxon.DateTime.fromISO(endDateStr);

    if (!startDt.isValid || !endDt.isValid) {
        console.error("Invalid date strings provided for summary:", startDateStr, endDateStr);
        return summaryData; // Return empty data on error
    }

    // Ensure the end date includes the whole day for comparison
     endDt = endDt.endOf('day');

    // Iterate through each day in the range
    let currentDt = startDt;
    while (currentDt <= endDt) {
        const dateStr = currentDt.toISODate(); // Format as 'YYYY-MM-DD'
        summaryData.dateLabels.push(dateStr); // Add date to labels
        summaryData.daily[dateStr] = {}; // Initialize daily data for this date

        const dailyLogs = logEntries[dateStr] || []; // Get logs for the current date

        dailyLogs.forEach(entry => {
            const projectId = entry.projectId || DEFAULT_PROJECT_ID;
            const duration = entry.duration || 0;

            // Aggregate total time per project
            summaryData.totals[projectId] = (summaryData.totals[projectId] || 0) + duration;

            // Aggregate daily time per project
            summaryData.daily[dateStr][projectId] = (summaryData.daily[dateStr][projectId] || 0) + duration;
        });

        // Move to the next day using Luxon
        currentDt = currentDt.plus({ days: 1 });
    }

    console.log("Generated Aggregated Summary Data:", summaryData);
    return summaryData;
}

/**
 * Renders the aggregated summary UI (text totals and line chart).
 * @param {object} summaryData - The data generated by generateAggregatedSummary.
 */
function renderAggregatedSummaryUI(summaryData) {
    if (!aggregatedSummaryTextContainer || !aggregatedLineChartCanvas) {
        console.error("Aggregated summary UI elements not found.");
        return;
    }

    // --- Render Text Summary ---
    aggregatedSummaryTextContainer.innerHTML = ''; // Clear previous summary
    const sortedProjectIds = Object.keys(summaryData.totals).sort((a, b) => summaryData.totals[b] - summaryData.totals[a]); // Sort by total time desc

    if (sortedProjectIds.length === 0) {
        aggregatedSummaryTextContainer.innerHTML = '<p class="text-gray-500 dark:text-gray-400 italic">No logged time found for the selected date range.</p>';
    } else {
         const heading = document.createElement('h3');
         heading.className = "text-lg font-semibold text-gray-700 dark:text-gray-200 border-b dark:border-gray-600 pb-1 mb-2";
         heading.textContent = "Totals by Project";
         aggregatedSummaryTextContainer.appendChild(heading);

        sortedProjectIds.forEach(projectId => {
            const project = projects.find(p => p.id === projectId);
            const projectName = project ? project.name : (projectId === DEFAULT_PROJECT_ID ? 'Inbox' : 'Other/Deleted');
            const projectColor = project ? project.color : DEFAULT_PROJECT_COLOR;
            const totalMinutes = summaryData.totals[projectId];

            const itemDiv = document.createElement('div');
            itemDiv.className = 'project-summary-item';
            itemDiv.innerHTML = `
                <span class="project-name">
                    <span class="project-color-swatch" style="background-color: ${projectColor};"></span>
                    <span class="truncate" title="${projectName}">${projectName}</span>
                </span>
                <span class="project-time">${formatDuration(totalMinutes)}</span>
            `;
            aggregatedSummaryTextContainer.appendChild(itemDiv);
        });
    }

    // --- Render Line Chart ---
    renderAggregatedLineChart(summaryData);
}


/**
 * Renders the aggregated summary line chart.
 * @param {object} summaryData - The data generated by generateAggregatedSummary.
 */
function renderAggregatedLineChart(summaryData) {
    if (!aggregatedLineChartCanvas) return;

    // Destroy previous chart instance if it exists
    if (aggregatedChartInstance) {
        aggregatedChartInstance.destroy();
        aggregatedChartInstance = null;
    }

    // If no daily data or dates, hide canvas and exit
    if (!summaryData.dateLabels || summaryData.dateLabels.length === 0) {
        aggregatedLineChartCanvas.style.display = 'none';
        return;
    }

    aggregatedLineChartCanvas.style.display = 'block'; // Ensure canvas is visible
    const ctx = aggregatedLineChartCanvas.getContext('2d');
    const isDark = htmlElement.classList.contains('dark');
    const gridColor = isDark ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)';
    const labelColor = isDark ? '#d1d5db' : '#374151'; // Gray-300 dark, Gray-700 light

    // --- Prepare Chart Datasets ---
    const datasets = [];
    // Get all unique project IDs present in the daily data across the range
    const projectIdsInData = new Set();
    summaryData.dateLabels.forEach(dateStr => {
        if (summaryData.daily[dateStr]) { // Check if data exists for the date
            Object.keys(summaryData.daily[dateStr]).forEach(projId => {
                projectIdsInData.add(projId);
            });
        }
    });

    projectIdsInData.forEach(projectId => {
        const project = projects.find(p => p.id === projectId);
        const projectName = project ? project.name : (projectId === DEFAULT_PROJECT_ID ? 'Inbox' : 'Other/Deleted');
        const projectColor = project ? project.color : DEFAULT_PROJECT_COLOR;

        const dataPoints = summaryData.dateLabels.map(dateStr => {
            // Get minutes for this project on this day, default to 0 if date or project entry missing
            return (summaryData.daily[dateStr] && summaryData.daily[dateStr][projectId]) ? summaryData.daily[dateStr][projectId] : 0;
        });

        datasets.push({
            label: projectName,
            data: dataPoints,
            borderColor: projectColor,
            backgroundColor: projectColor + '80', // Add some transparency for fill/points
            tension: 0.1, // Slight curve to lines
            fill: false, // Don't fill under the line
            pointRadius: 3,
            pointHoverRadius: 5,
        });
    });


    // --- Create Chart ---
    aggregatedChartInstance = new Chart(ctx, {
        type: 'line',
        data: {
            labels: summaryData.dateLabels, // Dates on X-axis
            datasets: datasets
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    position: 'bottom',
                    labels: {
                        color: labelColor,
                        boxWidth: 12,
                        font: { size: 10 }
                    }
                },
                tooltip: {
                    mode: 'index', // Show all datasets for the hovered date
                    intersect: false,
                    callbacks: {
                        label: function(context) {
                            let label = context.dataset.label || '';
                            if (label) { label += ': '; }
                            if (context.parsed.y !== null) { label += `${context.parsed.y} min`; }
                            return label;
                        }
                    }
                }
            },
            scales: {
                x: {
                    type: 'time', // Use time scale for dates
                    adapters: { // Ensure adapter is configured
                        date: {
                            locale: 'en-US' // Or appropriate locale
                        }
                    },
                    time: {
                        unit: 'day',
                        tooltipFormat: 'DDD', // Format for tooltip (e.g., "Mar 31, 2025") - Luxon format
                        displayFormats: {
                            day: 'MMM d' // Format for axis labels (e.g., "Mar 31")
                        }
                    },
                    title: {
                        display: true,
                        text: 'Date',
                        color: labelColor
                    },
                    ticks: {
                        color: labelColor,
                        maxRotation: 0, // Prevent label rotation if possible
                        autoSkip: true,
                        maxTicksLimit: 10 // Limit number of date ticks shown
                    },
                    grid: {
                        color: gridColor
                    }
                },
                y: {
                    beginAtZero: true,
                    title: {
                        display: true,
                        text: 'Time Spent (minutes)',
                        color: labelColor
                    },
                     ticks: {
                        color: labelColor,
                        // Optional: callback to format ticks if needed
                        // callback: function(value) { return value + ' m'; }
                    },
                    grid: {
                        color: gridColor
                    }
                }
            },
            interaction: { // Improve hover interaction
                mode: 'index',
                intersect: false,
            },
        }
    });
}

/**
 * Formats duration in minutes to a more readable string (e.g., "1h 30m", "45m").
 * @param {number} totalMinutes - The total duration in minutes.
 * @returns {string} - The formatted duration string.
 */
function formatDuration(totalMinutes) {
    if (totalMinutes === undefined || totalMinutes === null || totalMinutes < 0) return "0m";
    const hours = Math.floor(totalMinutes / 60);
    const minutes = totalMinutes % 60;
    let result = '';
    if (hours > 0) {
        result += `${hours}h`;
    }
    if (minutes > 0) {
        result += `${hours > 0 ? ' ' : ''}${minutes}m`; // Add space if hours exist
    }
    if (result === '') {
        result = '0m'; // Show 0m if both are zero
    }
    return result;
}
